# data
max_seq_size: 200
fps: 25
pose: "openpose"
pose_components: null
dataset: "hamnosys"
leave_out: ""

# training
no_wandb: True
seed: 42
num_gpus: 1
batch_size: 16
optimizer: "Adam"
lr: 0.001
max_epochs: 2000
noise_epsilon: 0.0001
tf_p: 0.5
seq_len_weight: 0.00002

# model
hidden_dim: 128
text_encoder_depth: 2
pose_encoder_depth: 4
encoder_heads: 2
num_steps: 10
separate_positional_embedding: True
num_pose_projection_layers: 1
encoder_dim_feedforward: 2048
model_variant: "baseline"
text_encoder_type: "transformer"
text_pose_encoder_type: "transformer"
pose_projection_type: "linear"
kan_hidden_dim: 64
model_name: "ham2pose-baseline"
ckpt: "checkpoints"
output_dir: "videos"
